apiVersion: v1
kind: ConfigMap
metadata:
  name: my-postgres-db-configmap
data:
  DB_NAME: "mydatabase"
  DB_USER: "myuser"
  DB_HOST: "my-postgres-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
---
